spring:
  amqp:
    deserialization:
      trust-all: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  elasticsearch:
    uris: http://localhost:9200

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

jwt:
  admin-secret: OjKBJybhfKfTSA+3ccyBaJD+3TzxVN/FmhF5jFlshrs=
  portal-secret: Tunyyqt8Sjeu1DJ9HvGie2e9aVBa23Z3w5eYDeHnoF0=

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: mall-quuj
